services:
  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: centrifugo server --config=/centrifugo/config.json
    ports:
      - "8000:8000"
    volumes:
      - ./cmd/centrifugo/config.json:/centrifugo/config.json
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: centrifugo-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
