services:
  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: centrifugo -c /centrifugo/config.json
    network_mode: host
    volumes:
      - ./cmd/centrifugo/config.json:/centrifugo/config.json

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    network_mode: host
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.listen-address=:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
